# Generated by Django 4.0.2 on 2022-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Overview', models.CharField(max_length=255, null=True)),
                ('Category', models.CharField(max_length=20, null=True)),
                ('Urgency', models.CharField(max_length=20, null=True)),
                ('CreationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=60, null=True)),
                ('Department', models.CharField(max_length=20, null=True)),
                ('AccountCreationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
