# Generated by Django 4.0.2 on 2022-03-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stub',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='Completed',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='CreationDate',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='EstimatedCompletionTime',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='EstimatedCompletionTimeUOM',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='InProcess',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='IssuerUserFileID',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='Overview',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='PriorityInQueue',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='RecipientUserFileID',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='Urgency',
        ),
    ]
