# Generated by Django 4.0.2 on 2022-02-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0002_rename_userfile_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
    ]
