# Generated by Django 4.0.2 on 2022-03-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0002_remove_stub_category_remove_stub_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stubattachment',
            name='StubID',
        ),
        migrations.DeleteModel(
            name='Stub',
        ),
        migrations.DeleteModel(
            name='StubAttachment',
        ),
    ]
