# Generated by Django 4.0.2 on 2022-03-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0003_remove_stubattachment_stubid_delete_stub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Overview', models.CharField(max_length=65535)),
                ('Category', models.CharField(choices=[('Request', 'Request'), ('Bug', 'Bug'), ('New Feature', 'New Feature'), ('Upgrade', 'Upgrade'), ('Improvement', 'Improvement'), ('Suggestion', 'Suggestion'), ('System Failure', 'System Failure')], max_length=14)),
                ('Urgency', models.CharField(choices=[('Immediate', 'Immediate'), ('Highly Important', 'Highly Important'), ('Important', 'Important'), ('Somewhat Important', 'Somewhat Important'), ('When You Have Time', 'When You Have Time')], max_length=18)),
                ('Domain', models.CharField(max_length=20)),
                ('StartDate', models.DateTimeField(null=True)),
                ('EstimatedCompletionTime', models.IntegerField(null=True)),
                ('EstimatedCompletionTimeUOM', models.CharField(max_length=1, null=True)),
                ('PriorityInQueue', models.FloatField(null=True)),
                ('InProcess', models.BooleanField()),
                ('Completed', models.BooleanField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('IssuerUserFileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IssuerUserFileID', to='stubbit.userfile')),
                ('RecipientUserFileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipientUserFileID', to='stubbit.userfile')),
            ],
        ),
        migrations.CreateModel(
            name='StubAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalSize', models.FloatField()),
                ('CompressedSize', models.FloatField()),
                ('FileServerPath', models.CharField(max_length=255)),
                ('StubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stubbit.stub')),
            ],
        ),
    ]
