# Generated by Django 4.0.2 on 2022-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0004_stub_stubattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='LastIPAddress',
            field=models.CharField(default='', max_length=15),
        ),
    ]
