# Generated by Django 4.0.2 on 2022-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0005_usermeta_lastipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='LoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
