# Generated by Django 4.0.2 on 2022-02-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0005_alter_stub_urgency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Account',
        ),
    ]
