# Generated by Django 4.0.2 on 2022-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0006_rename_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stub',
            name='Overview',
            field=models.TextField(null=True),
        ),
    ]
