# Generated by Django 4.0.2 on 2022-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0007_alter_stub_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgName', models.CharField(max_length=50, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('PhoneNumber', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='Department',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='stub',
            name='Category',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
