# Generated by Django 4.0.2 on 2022-03-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0007_remove_usermeta_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='AccountCreationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='LastIPAddress',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='LastLogInDate',
            field=models.DateTimeField(null=True),
        ),
    ]
