# Generated by Django 4.0.2 on 2022-02-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0008_organization_alter_account_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='OrgName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='PhoneNumber',
            new_name='Phone',
        ),
    ]
