# Generated by Django 4.0.2 on 2022-03-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0008_alter_usermeta_accountcreationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='Name',
            field=models.CharField(default='', max_length=510),
        ),
    ]
