# Generated by Django 4.0.2 on 2022-03-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0009_userfile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StubAttachment',
        ),
    ]
