# Generated by Django 4.0.2 on 2022-02-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0009_rename_orgname_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='OrganizationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stubbit.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='State',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
