# Generated by Django 4.0.2 on 2022-02-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0010_account_organizationid_organization_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stub',
            name='Issuer',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Stub',
        ),
    ]
