# Generated by Django 4.0.2 on 2022-02-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stubbit', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='LicenseID',
        ),
        migrations.RemoveField(
            model_name='stub',
            name='DeveloperUserFileID',
        ),
        migrations.RemoveField(
            model_name='stubattachment',
            name='StubID',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='OrganizationID',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='UserFileID',
        ),
        migrations.RemoveField(
            model_name='userpass',
            name='UserFileID',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Stub',
        ),
        migrations.DeleteModel(
            name='StubAttachment',
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
        migrations.DeleteModel(
            name='UserMeta',
        ),
        migrations.DeleteModel(
            name='UserPass',
        ),
    ]
